Repository goaop/framework, pull requests merged in 2019-01, with the labels that each got.

#398 Reflection getFileName fix
  src/Instrument/Transformer/MagicConstantTransformer.php
  tests/Fixtures/project/src/Application/Main.php
  tests/Fixtures/project/src/Aspect/InitializationAspect.php
  tests/Go/Functional/BaseFunctionalTest.php
  tests/Go/Functional/ReflectionFilenameTest.php
Labels: Improvement

#402 optimalization of the file system enumerator, which now uses the glob function (in Symfony Finder)
  composer.json
  src/Instrument/FileSystem/Enumerator.php
  tests/Go/Instrument/FileSystem/EnumeratorTest.php
Labels: Improvement, Performance

#406 Bump phpunit to latest version
  composer.json
  phpunit.xml.dist
  tests/Go/Aop/Bridge/Doctrine/MetadataLoadInterceptorTest.php
  tests/Go/Aop/Framework/AbstractInterceptorTest.php
  tests/Go/Aop/Framework/AbstractJoinpointTest.php
  tests/Go/Aop/Framework/AbstractMethodInvocationTest.php
  tests/Go/Aop/Framework/ClassFieldAccessTest.php
  tests/Go/Aop/Framework/DynamicClosureSplatMethodInvocationTest.php
  tests/Go/Aop/Framework/StaticClosureMethodInvocationTest.php
  tests/Go/Aop/Pointcut/PointcutParserTest.php
  tests/Go/Aop/Pointcut/SignaturePointcutTest.php
  tests/Go/Aop/Support/AndPointFilterTest.php
  tests/Go/Aop/Support/NotPointFilterTest.php
  tests/Go/Aop/Support/OrPointFilterTest.php
  tests/Go/Aop/Support/TruePointFilterTest.php
  tests/Go/Core/AdviceMatcherTest.php
  tests/Go/Core/GoAspectContainerTest.php
  tests/Go/Functional/BaseFunctionalTest.php
  tests/Go/Instrument/FileSystem/EnumeratorTest.php
  tests/Go/Instrument/PathResolverTest.php
  tests/Go/Instrument/Transformer/ConstructorExecutionTransformerTest.php
  tests/Go/Instrument/Transformer/FilterInjectorTransformerTest.php
  tests/Go/Instrument/Transformer/MagicConstantTransformerTest.php
  tests/Go/Instrument/Transformer/SelfValueTransformerTest.php
  tests/Go/Instrument/Transformer/WeavingTransformerTest.php
  tests/Go/PhpUnit/ClassIsNotWovenConstraint.php
  tests/Go/PhpUnit/ClassMemberNotWovenConstraint.php
  tests/Go/PhpUnit/ClassMemberWovenConstraint.php
  tests/Go/PhpUnit/ClassWovenConstraint.php
  tests/Go/Proxy/ClassProxyGeneratorTest.php
  tests/Go/Proxy/Part/FunctionCallArgumentListGeneratorTest.php
  tests/Go/Proxy/Part/FunctionParameterListTest.php
  tests/Go/Proxy/Part/InterceptedConstructorGeneratorTest.php
  tests/Go/Proxy/Part/InterceptedFunctionGeneratorTest.php
  tests/Go/Proxy/Part/InterceptedMethodGeneratorTest.php
  tests/Go/Proxy/Part/JoinPointPropertyGeneratorTest.php
Labels: Improvement, Tests

#407 Add ability for strict_types in proxy class.
  src/Instrument/Transformer/WeavingTransformer.php
  tests/Go/Instrument/Transformer/WeavingTransformerTest.php
  tests/Go/Instrument/Transformer/_files/class-proxy.php
  tests/Go/Instrument/Transformer/_files/php7-class-proxy.php
  tests/Go/Instrument/Transformer/_files/php7-class-woven.php
  tests/Go/Instrument/Transformer/_files/php7-class.php
Labels: Feature

#410 Bump supported php version to ~7.0
  .travis.yml
  README.md
  appveyor.yml
  composer.json
Labels: Improvement
